name: attendance
pack: harold
description: Gatilho Responsável Pela Troca do Responsável do Atendimento do Usuário entre o Harold e um Humano
enabled: true

trigger:
    type: core.st2.webhook
    parameters:
        url: "harold/attendance"

action:
    ref: harold.attend
    parameters:
        userid: "{{trigger.body.userid}}"
        status: "{{trigger.body.status}}"