name: attendance
pack: harold
description: Trigger for response exchange by user service
enabled: true

trigger:
    type: core.st2.webhook
    parameters:
        url: "harold/attendance"

action:
    ref: core.attend
    parameters:
        userid: "{{trigger.body.userid}}"
        status: "{{trigger.body.status}}"