name: controller
pack: harold
description: Webhook para controle do responsável pelo atendimento.
enabled: true

trigger:
    type: core.st2.webhook
    parameters:
        url: "oop/controller"

action:
    ref: harold.service
    parameters:
        question: "{{trigger.body.text}}"
        username: "{{trigger.body.username}}"
        userid: "{{trigger.body.userid}}"