name: predict
pack: harold
description: Harold bot classifier for a webhook text message
enabled: true

trigger:
    type: core.st2.webhook
    parameters:
        url: "harold/message"

action:
    ref: harold.message
    parameters:
        question: "{{trigger.body.text}}"
        username: "{{trigger.body.username}}"
        userid: "{{trigger.body.id}}"