name: publish
pack: harold
description: Publisher webhook de envio de mensagens para o bot do harold.
enabled: true

trigger:
    type: core.st2.webhook
    parameters:
        url: "harold/message"

action:
    ref: harold.message
    parameters:
        message: "{{trigger.body.message}}"
        username: "{{trigger.body.username}}"
        userid: "{{trigger.body.userid}}"