name: publish
pack: harold
description: Publisher webhook de envio de mensagens para o bot do harold.
enabled: true

trigger:
    type: core.st2.webhook
    parameters:
        url: "harold/publish"

action:
    ref: harold.message
    parameters:
        question: "{{trigger.body.text}}"
        username: "{{trigger.body.username}}"
        userid: "{{trigger.body.userid}}"