name: subscribe
pack: harold
description: Subscriber webhook para receber as respostas de mensagens do harold.
enabled: true

trigger:
    type: core.st2.webhook
    parameters:
        url: "harold/subscribe"

action:
    ref: core.local
    parameters:
        cmd: "echo \"{{trigger.body}}\" >> ~/st2.harold.out ; sync"